### ISSUE TITLE
"Using ISOs" for Linux?

### ISSUE THREAD

**Issue by fdschonborn** [MicrosoftDocs/windows-insider#307]
https://docs.microsoft.com/en-us/windows-insider/isos

The documentation only has instructions for Windows, some people may be looking to move from Linux to a fresh copy of an Insider build of Windows (or a stable one, for that matter).

Linux ISOs are commonly written to a USB drive using the `dd` utility, but it doesn't seem to work with Windows ISOs. As a result of that the [WoeUSB](https://github.com/woeusb) project provides a software that can create bootable USBs of Windows without any issues (although, of course, they cannot be booted if Secure Boot is enabled).

**Comment by yogkumgit** [comment]
@bleblancMSFT Please help us in resolving this issue. Thanks

**Comment by rubyFeedback** [comment]
Oddly enough, while I have tons of USB devices, I still burn this onto a DVD. Somehow I find it easier to keep a backup stack of DVDs; my USB devices tend to be too "volatile" in use (because I don't recall where I put them and what I put on any USB device, whereas with a DVD I write down on top what this is).

But I agree that bootable devices are super-useful. Making the process streamlined and simple would be nice. I don't really use dd myself but instead use growisofs/dvd-rw-tools, but I know several guides that use just dd these days. Creating a bootable USB for windows would be super-convenient - I am pretty certain this is already possible, but I guess people may have to search the www a little bit to find out. Whereas a specialized widget or tool may be better.

**Comment by riverar** [comment]
@fdschonborn Seems like a neat suggestion.

@yogkumgit @bleblancMSFT Are you tracking Suggestions/Enhancements in this repository? Or maybe extract it for internal use and close this issue?
